### ISSUE TITLE
Support for "recursive" endpoints

### ISSUE THREAD

**Issue by stevenosloan** [stevenosloan/middleman-data_source#2]
Currently you must specify the *specific* url any resource lives at, this is great if all the data is in one place. *But*, if you are attempting to pull data from a RESTful (ish) api this falls flat.

Consider this made up example where we want to pull blog posts:
```yaml
# /api/posts.yml
- title: Foo
  excerpt: |
    Lorem Ipsum
  author: /api/authors/bar.yml
  href: /api/posts/foo.yml
  url: /posts/foo
- title: Wu
  author: /api/authors/tang.yml
  excerpt: |
    Lorem Ipsums/tang.yml
  href: /api/posts/foo.yml
  url: /posts/wu

# /api/posts/foo.yml
title: Foo
author: /api/authors/bar.yml
url: /posts/foo
content: |
  Lorem ipsum exciting post about things.

# /api/authors/bar.yml
name: Bar
```

We would want to write our index something like:

```haml
- data.posts.each do |post|
  %article
    %h1= post.title
    %p= post.author.name
    %a{ href: post.url } Read More
```

I'm not sure how (or if) to pull this off. There would definitely need to be some sort of user mapping between the index/individual resources. That may get too complicated to include -- but figuring out a good API to allow it to be injected would be a start.
